### PR TITLE
TNW reponsive design

### PR DESCRIPTION
**Pull request by kcotrinam**
### Responsive TNW Website

We have used cutting-edge technologies to create this responsive website: 

- HTML5 
- CSS3: Flexbox, Css grid, float and media query technologies

### CODE REVIEW

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team 👋 
Status: Changes Required ♻️ 

Your project looks really great! Eye-catching and it is obvious that you know what you are doing.
Let's cover a few more details to carry this beauty further away... ✊ 

### Readme

- [x]  Please fix the broken image link. (It seems like it has the correct path, but I see it as a broken image)

### Large Size
> Navigation Bar

- [x]  TNW logo(on the left side of the navbar) **should start to appear on the medium size**. Currently, we can see the TNW logo in the large size too. 🚫 Please carefully check for the large size to correctly position the TNW logo. It should be on the left top part of the first article image.

### General Layout

- [x]  Latest Fundings Section has a minor type "fundin": please fix that. 🙏 

### [OPTIONAL]

- [x]  Please consider using **main** tag to have a semantically better structure.

## That's it, you can request another code review after applying these changes.

With all my respect... 🙏

**Comment by martinnajjar12** [comment]
> Hello Team 👋
> Status: Changes Required ♻️
> 
> Your project looks really great! Eye-catching and it is obvious that you know what you are doing.
> Let's cover a few more details to carry this beauty further away... ✊
> 
> ### Readme
> * [x]   Please fix the broken image link. (It seems like it has the correct path, but I see it as a broken image)
> 
> ### Large Size
> > Navigation Bar
> 
> * [x]   TNW logo(on the left side of the navbar) **should start to appear on the medium size**. Currently, we can see the TNW logo in the large size too. 🚫 Please carefully check for the large size to correctly position the TNW logo. It should be on the left top part of the first article image.
> 
> ### General Layout
> * [x]   Latest Fundings Section has a minor type "fundin": please fix that. 🙏
> 
> ### [OPTIONAL]
> * [x]   Please consider using **main** tag to have a semantically better structure.
> 
> ## That's it, you can request another code review after applying these changes.
> With all my respect... 🙏

teşekkür ederim 🙏 ;)

**Review by kevcap — APPROVED** [review]
# [STATUS] PROJECT APPROVED 🍾

## Congratulations team! Good job making my previously requested changes and thanks for making the optional changes also, that's awesome guys! 🐱‍👓👏👏

### _Great work, your clone looks almost identic,  you have also followed the best practices throughout the code, you guys got my attention and have my approval to move on!_ 🥇💯

## [OPTIONAL CHANGES]
- [ ] Improve the name of your classes to make it more descriptive, so other developer can know what it actually does. 💪
image

⚠ These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:

- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
image
## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Comment by martinnajjar12** [comment]
> # [STATUS] PROJECT APPROVED 🍾
> ## Congratulations team! Good job making my previously requested changes and thanks for making the optional changes also, that's awesome guys! 🐱‍👓👏👏
> ### _Great work, your clone looks almost identic, you have also followed the best practices throughout the code, you guys got my attention and have my approval to move on!_ 🥇💯
> ## [OPTIONAL CHANGES]
> * [ ]  Improve the name of your classes to make it more descriptive, so other developer can know what it actually does. 💪
>   image
> 
> ⚠ These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:
> 
> * [ ]  Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
>   Take a look at this example:
>   image
>   Your HTML will be something like this:
>   image
>   Apply the same logic above in **ALL** those repeated rules listed below:
>   image
> 
> ## As always, I wish you all the very best and see you both at the top🚀
> 👨🏻‍💻 **TSE: Kevin Alves**
> 
> 📫 Have any question? Better call Kevin:
> 
> [ gmail](mailto:kevinalves.js@gmail.com) [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

Thank you so much!

**Pull request merged**
